name: UpdateCards

on:
  push:
    branches:
      - dev
  schedule:
    - cron: "34 3 * * *"

jobs:
  update-cards:
    name: Update repoository cards and a language card
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          repository: "NaokiHori/NaokiHori"
          ref: dev
      - name: Prepare place for artifacts
        run: |
          if [ ! -e card ]; then
            mkdir card
          fi
      - name: Update repoository cards
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            python \
            scripts/repository_cards/main.py \
            --config-dir=scripts/config \
            --out-dir=card \
            --template-svg-file=scripts/repository_cards/template.svg
      - name: Update language card
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            python \
            scripts/language_card/main.py \
            --config-dir=scripts/config \
            --out-dir=card \
            --template-svg-file=scripts/language_card/template.svg
      - name: Commit changes
        run: |
          git switch -c card
          git config --local user.email "36466440+NaokiHori@users.noreply.github.com"
          git config --local user.name "NaokiHori"
          git add card
          git commit -m "Update cards" -a || true
          git push -f origin card

