name: UpdateAssets

on:
  workflow_run:
    workflows:
      - UpdateReadme
    types:
      - completed
  schedule:
    - cron: "34 3 * * 0"

permissions:
  contents: write

jobs:
  update-and-push:
    name: Update assets and push
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
          cache: true
      - name: Prepare and Generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p newassets
          cd scripts/update_assets
          go build -o update_assets_bin .
          cd ../..
          ./scripts/update_assets/update_assets_bin \
            --config-dir=scripts/config \
            --out-dir=newassets \
            --template-dir=scripts/update_assets/view
      - name: Commit and Push
        run: |
          git config --local user.email "36466440+NaokiHori@users.noreply.github.com"
          git config --local user.name "NaokiHori"
          mkdir -p assets
          mv newassets/* assets/
          git switch main
          git add assets
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update assets"
            git push -f origin main
          fi
