name: UpdateCards

on:
  push:
    branches:
      - dev
  schedule:
    - cron: "34 3 * * *"

jobs:
  update-cards:
    name: Update repoository cards and a language card
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          repository: "NaokiHori/NaokiHori"
          ref: dev
      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: 1.21.5
      - name: Prepare place for artifacts
        run: |
          if [ ! -e card ]; then
            mkdir card
          fi
      - name: Update language and repoository cards
        run: |
          cd scripts/cards
          go build .
          cd ../..
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            ./scripts/cards/create_cards \
            --config-dir=scripts/config \
            --out-dir=card \
            --template-dir=scripts/cards/view
      - name: Commit changes
        run: |
          git switch -c card
          git config --local user.email "36466440+NaokiHori@users.noreply.github.com"
          git config --local user.name "NaokiHori"
          git add card
          git commit -m "Update cards" -a || true
          git push -f origin card

